### ISSUE TITLE
Del key inserts in ASCII Mode 0x7f instead of deleting bytes

### ISSUE THREAD

**Issue by Simsys** [Simsys/qhexedit2#60]

**Comment by firexx** [comment]
@Simsys 
confirm. because the .text() returns 0x7f on "del" keypressed and this going into replace. probably we have to rewrite keypressevent to catch all keys that changes text formatting then exit from the function. if nothing was catched before then insert/replace the pressed key as char.

what do you think about?

**Comment by Simsys** [comment]
fixed, see 180e0bc8547c8d8089b6d984f7a9699311105a6b
