### ISSUE TITLE
Selected locations zeroed

### ISSUE THREAD

**Issue by lancos** [Simsys/qhexedit2#86]
If you select more locations
![snapshot29](https://user-images.githubusercontent.com/15278592/28234577-85ec06de-6901-11e7-9baa-de97666c5c75.png)

and then type a number, for example 7, all selected locations are zeroed
![snapshot30](https://user-images.githubusercontent.com/15278592/28234584-9a6ebc64-6901-11e7-9f4a-e4a25ff33568.png)

and undo doesn't reverse the operation.

**Comment by Simsys** [comment]
Hi lancos,

I see no fault in this behaviour. If you select characters in a text editor and then enter a character, the selected text is deleted. This happens regardless of whether the insert mode has been activated or not.

The behavior of QHexEdit is identical if the insert mode is activated. In overwrite mode, however, the selected characters are set to 0. This behavior is desirable, because the file length in overwrite mode must not change. One could discuss here that the marked part should remain unchanged. But why does the user mark before the input? I find this behaviour acceptable.

Undo works for me here, unlike you described.
